# Price-to-Operating Cash Flow Calculation
# ----------------------------------------
# Overview:
# The Price-to-Operating Cash Flow ratio (P/OCF) measures the valuation of a company 
# relative to its operating cash flow. This ratio is particularly useful for companies 
# where cash flow is a more relevant metric than earnings, such as firms with significant 
# non-cash expenses or those in capital-intensive industries.
#
# Desired Value:
# A lower P/OCF ratio may suggest that a company is undervalued. However, it's important 
# to compare this ratio with peer companies in the same industry. A firm's growth prospects, 
# stability of cash flows, and industry dynamics should also be considered.
#
# Note: This script uses hard-coded values. For real-world application, input data 
# should be sourced from financial statements and market data.

def convert_to_actual_value(value):
    """Converts the value in the format of 1.00 to actual $1 million."""
    return value * 1000000

def p_to_ocf_ratio(market_cap, operating_cash_flow):
    """
    Calculate P/OCF ratio.
    
    Parameters:
    market_cap - Company's market capitalization
    operating_cash_flow - Operating cash generated by the company
    """
    return market_cap / operating_cash_flow

# Hard-coded values for demonstration:
# Company's metrics
company_market_cap = convert_to_actual_value(3141.32)  # Company's market capitalization
company_operating_cash_flow = convert_to_actual_value(1583.00)  # Operating cash flow of the company

# Industry averages
industry_market_cap_avg = convert_to_actual_value(44750.00)  # Average market capitalization in the industry
industry_operating_cash_flow_avg = convert_to_actual_value(2950.00)  # Average operating cash flow in the industry

# Calculate P/OCF for the company and the industry
company_p_ocf_ratio = p_to_ocf_ratio(company_market_cap, company_operating_cash_flow)
industry_p_ocf_ratio = p_to_ocf_ratio(industry_market_cap_avg, industry_operating_cash_flow_avg)

# Calculate the difference between the company's P/OCF and the industry average
p_ocf_difference = company_p_ocf_ratio - industry_p_ocf_ratio

# Output the results
print("Price-to-Operating Cash Flow Calculation:\n")
print(f"Company P/OCF Ratio: {company_p_ocf_ratio:.2f}")
print(f"Industry Average P/OCF Ratio: {industry_p_ocf_ratio:.2f}")
print(f"Difference between Company and Industry P/OCF: {p_ocf_difference:.2f}")

if p_ocf_difference < 0:
    print("The company has a lower P/OCF ratio than the industry average, potentially indicating it's undervalued.")
elif p_ocf_difference == 0:
    print("The company's P/OCF ratio is in line with the industry average.")
else:
    print("The company has a higher P/OCF ratio than the industry average, which may indicate overvaluation.")
